# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "BearGN"
license = "MIT"
licenselink = "https://github.com/MohamedElashri/beargn/blob/main/LICENSE"
description = "A green variant of the Bear Blog theme with a nature-inspired minimalist design"
homepage = "https://github.com/MohamedElashri/beargn"
tags = ["blog", "clean", "customizable", "dark mode", "fast", "light", "minimal", "minimalist", "mobile", "modern", "responsive", "simple", "green", "nature"]
features = ["blog", "clean", "customizable", "dark mode", "fast", "light", "minimal", "minimalist", "mobile", "modern", "responsive", "simple"]
min_version = "0.41.0"

[author]
  name = "Mohamed Elashri"
  homepage = "https://melashri.net"

[original]
  name = "Bear Blog"
  homepage = "https://bearblog.dev"
  repo = "https://github.com/janraasch/hugo-bearblog"
